stages:
    - build
    - deploy
build:
    stage: build
    image: "node:18.12.1-alpine3.16"
    script:
        - echo "Building deploy package"
        - npm install
        - npm run build
        - echo "Build successful"
    artifacts:
        expire_in: 1 month
        paths:
            - build

deploy:
    variables:
      AWS_DEFAULT_REGION: us-west-1
    stage: deploy
    dependencies:
        - build
    image: "amazon/aws-cli:2.8.11"
    script:
        - ls build/
        - aws s3 sync --delete build s3://artsite-site/
    only:
        refs:
            - main
