stages:
  - build
  - deploy
build:
  stage: build
  image: "node:18.12.1-alpine3.16"
  script:
    - echo "Building deploy package"
    - npm install
    - npm run build
    - echo "Build successful"
  artifacts:
    expire_in: 1 month
    paths:
      - build

deploy:
  stage: deploy
  dependencies:
    - build
  image: "amazon/aws-cli:2.8.11"
  script:
    - s3 sync --delete build s3://artsite-site/
  only:
    refs:
      - main
